version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "friday"
          time: "09:00"
          timezone: "Asia/Taipei"
      open-pull-requests-limit: 3
      groups:
          regular-dependencies:
              exclude-patterns:
                  - "*storybook*"
                  - "*electron*"
                  - "jotai"
                  - "react"
                  - "@types/react"
                  - "*react-dom"
                  - "*docusaurus*"
              update-types:
                  - "patch"
                  - "minor"
          storybook:
              patterns:
                  - "*storybook*"
              update-types:
                  - "patch"
                  - "minor"
          electron:
              patterns:
                  - "*electron*"
              update-types:
                  - "patch"
                  - "minor"
          docusaurus:
              patterns:
                  - "*docusaurus*"
              update-types:
                  - "patch"
                  - "minor"
          react:
              patterns:
                  - "react"
                  - "@types/react"
                  - "*react-dom"
              update-types:
                  - "patch"
                  - "minor"
          jotai:
              patterns:
                  - "jotai"
              update-types:
                  - "patch"
                  - "minor"
    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "friday"
          time: "09:00"
          timezone: "Asia/Taipei"
      open-pull-requests-limit: 2
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "friday"
          time: "09:00"
          timezone: "Asia/Taipei"
      open-pull-requests-limit: 2
