version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "cron"
          cronjob: "0 9 1 1,3,5,7,9,11 *"
          timezone: "Asia/Taipei"
      allow:
          - dependency-name: "*"
            update-types:
                - "version-update:semver-patch"
      groups:
          dev-dependencies-patch:
              dependency-type: "development"
              exclude-patterns:
                  - "*storybook*"
                  - "*electron*"
                  - "jotai"
                  - "react"
                  - "@types/react"
                  - "*react-dom"
                  - "*docusaurus*"
              update-types:
                  - "patch"

          prod-dependencies-patch:
              dependency-type: "production"
              exclude-patterns:
                  - "*storybook*"
                  - "*electron*"
                  - "jotai"
                  - "react"
                  - "@types/react"
                  - "*react-dom"
                  - "*docusaurus*"
              update-types:
                  - "patch"

          storybook-patch:
              patterns:
                  - "*storybook*"
              update-types:
                  - "patch"

          electron-patch:
              patterns:
                  - "*electron*"
              update-types:
                  - "patch"

          docusaurus-patch:
              patterns:
                  - "*docusaurus*"
              update-types:
                  - "patch"

          react-patch:
              patterns:
                  - "react"
                  - "@types/react"
                  - "*react-dom"
              update-types:
                  - "patch"

          jotai-patch:
              patterns:
                  - "jotai"
              update-types:
                  - "patch"

    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
          interval: "cron"
          cronjob: "0 9 1 1,3,5,7,9,11 *"
          timezone: "Asia/Taipei"
      allow:
          - dependency-name: "*"
            update-types:
                - "version-update:semver-patch"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "cron"
          cronjob: "0 9 1 1,3,5,7,9,11 *"
          timezone: "Asia/Taipei"
      allow:
          - dependency-name: "*"
            update-types:
                - "version-update:semver-patch"
